#!/usr/bin/with-contenv bash

if [ -z ${ZULU_REPO_VER+x} ]; then
  export ZULU_REPO_VER=1.0.0-2
fi
if [ -z ${ZULU_JAVA_VER+x} ]; then
  export ZULU_JAVA_VER=11.0.11
fi
export ZULU_VER=${ZULU_JAVA_VER%%.*}

echo "**** installing zulu${ZULU_VER} ZULU_JAVA_VER=${ZULU_JAVA_VER} from ZULU_REPO_VER=${ZULU_REPO_VER} ****"
apt-get -qq update && \
    apt-get -qq -y --no-install-recommends install gnupg software-properties-common locales curl && \
    locale-gen en_US.UTF-8 && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9 && \
    curl -sLO https://cdn.azul.com/zulu/bin/zulu-repo_${ZULU_REPO_VER}_all.deb && dpkg -i zulu-repo_${ZULU_REPO_VER}_all.deb && \
    apt-get -qq update && \
    apt-get -qq -y dist-upgrade && \
    mkdir -p /usr/share/man/man1 && \
    apt-get -qq -y --no-install-recommends install zulu${ZULU_VER}-jdk=${ZULU_JAVA_VER}-* && \
    rm -rf zulu-repo_${ZULU_REPO_VER}_all.deb && \
    echo "**** apt cleanup ****" && \
    rm -rf /var/lib/apt/lists/*

export JAVA_HOME=$(find /usr/lib/jvm -type d -name "zulu*")
echo "**** computed JAVA_HOME=${JAVA_HOME} ****"

echo "**** ensuring JAVA_HOME is set ****"
sed -i '/^#!\/usr\/bin/a \\n# Added by code-server-mod-java\nexport JAVA_HOME='"${JAVA_HOME}" /etc/services.d/code-server/run

java --version

# Exit if NOT_INSTALL_MAVEN is not set
if [ $? -eq 0 ] && [ -z ${NOT_INSTALL_MAVEN+x} ]; then
  echo "**** proceeding to maven install ****"
else
  echo "**** skip maven install ****"
  exit 0
fi

if [ -z ${MAVEN_VERSION+x} ]; then
  export MAVEN_VERSION=3.6.3
fi
if [ -z ${MAVEN_SHA+x} ]; then
  export MAVEN_SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
fi

export MAVEN_BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${MAVEN_BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${MAVEN_SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

mvn -v

echo "**** apt cleanup ****"
rm -rf /var/lib/apt/lists/*